config/routes.rb
Rails.application.routes.draw do
  resources :pizza_toppings
  resources :restaurants
  resources :pizzas
  resources :toppings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
    has_many :pizza_toppings
    has_many :toppings, through: :pizza_toppings
    belongs_to :restaurant, optional: true

    def display_veg
        return self.vegetarian ? "Yes" : "No"
    end
end

app/models/pizza_topping.rb
class PizzaTopping < ApplicationRecord
    belongs_to :topping 
    belongs_to :pizza 
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :pizzas
    has_many :toppings
end

app/models/topping.rb
class Topping < ApplicationRecord
    has_many :pizza_toppings
    has_many :pizzas, through: :pizza_toppings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pizza_toppings_controller.rb
class PizzaToppingsController < ApplicationController
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController

    def index
        @pizzas = Pizza.all 
    end

    def show
        @pizza = Pizza.find(params[:id])
    end

    def new
        @pizza = Pizza.new
        @restaurants = Restaurant.all
    end

    def create
        name = params["pizza"]["name"]
        vegetarian = params["pizza"]["vegetarian"]
        restaurant = params["pizza"]["restaurant"]
            pizza = Pizza.create(name: name, vegetarian: vegetarian, restaurant: Restaurant.find(params["pizza"]["restaurant"]))
            # if params["pizza"]["topping1"] != ""
            #     pizza.toppings << Topping.find_or_create_by(name: params["pizza"]["topping1"])
            # end
            # if params["pizza"]["topping2"] != ""
            #     pizza.toppings << Topping.find_or_create_by(name: params["pizza"]["topping2"])
            # end
            # if params["pizza"]["topping3"] != ""
            #     pizza.toppings << Topping.find_or_create_by(name: params["pizza"]["topping3"])
            # end
            toppings = params["pizza"]["topping"]
            toppings.each do |topping|
                x = Topping.find_or_create_by(name: topping)
                pizza.toppings << x
            end
            redirect_to pizza_path(pizza.id)
    end

    def edit
        @pizza = Pizza.find(params[:id])
        @restaurants = Restaurant.all
        render :edit
    end

    def update
        @pizza = Pizza.update(params[:id])
        redirect_to pizzas_path
    end

    def destroy
        @pizza = Pizza.destroy(params[:id])
        redirect_to pizzas_path
    end

    # private

    # def pizza_params
    #   params.require(:pizza).permit(:name,:vegetarian, :restaurant_id)
    # end

end



# <%= form_for @pizza do |f| %>
#     <%= f.label :name, "Pizza Name:" %>
#     <%= f.text_field :name %>
#     <br><br>
#     <%= f.label :topping1 %>
#     <%= f.text_field :toppings %>
#     <br><br>
#     <%= f.label :topping2 %>
#     <%= f.text_field :toppings %>
#     <br><br>
#     <%= f.label :topping3 %>
#     <%= f.text_field :toppings %>
#     <br><br>
#     <%= f.label :vegetarian, "Vegetarian?" %>
#     <%= f.select :vegetarian, [true, false] %>
#     <br><br>
#     <%= f.collection_select(:restaurant_id, Restaurant.all, :id, :name) %>
#     <br><br>
#     <%= f.submit button_text %>
#   <% end %>

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    def index
        @restaurants = Restaurant.all 
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizza_toppings_helper.rb
module PizzaToppingsHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pizzahouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

<html>
<head>
<style>
body  {
  background-image: url("https://media.istockphoto.com/photos/black-brick-wall-dark-background-for-design-picture-id639173848?k=6&m=639173848&s=170667a&w=0&h=XqsulkBZnsd4ANbC46bLodBSfZTblmrWonP4mKM-5so=");
  background-color: #cccccc;
}
</style>
</head>
<body>



</body>
</html>

app/views/pizzas/_pizza_form.html.erb
<center><h4 style="font-size:20px ; color:#AC9F9A ; font-family:'Impact'">
<%= form_tag(pizza) do %> 
  <%= label_tag("pizza[name]", "Pizza Name:" )%> 
  <%= text_field_tag ("pizza[name]")%>
  <br><br>
  <%= label_tag("pizza[restaurant]", "Restaurant Name:")%>
  <%= select_tag("pizza[restaurant]", options_from_collection_for_select(@restaurants, :id, :name)) %>
  <br><br>
  <%= label_tag("pizza[topping]", "Topping 1:")%>
  <%= text_field_tag ("pizza[topping][]") %> 
  <br><br>
  <%= label_tag("pizza[topping]", "Topping 2:")%>
  <%= text_field_tag ("pizza[topping][]") %> 
  <br><br>
  <%= label_tag("pizza[topping]", "Topping 3:")%>
  <%= text_field_tag ("pizza[topping][]") %> 
  <br><br>
  <%= label_tag("pizza[vegetarian]", "Vegetarian?:")%> 
  <%= select_tag("pizza[vegetarian]", options_for_select([true, false])) %> 
  <br><br></h4></p>
  <%= submit_tag "PIZZA MAGIC", style: "font-size:30px" %>
  <%end%>
</center>

app/views/pizzas/edit.html.erb
<h1 style="font-size:30px ; color:white ; font-family: 'Impact'"> Edit Pizza </h1> 

<%= form_tag('/pizza') do %> 
  <%= label_tag("pizza[name]", "Pizza name:" )%> 
  <%= text_field_tag ("pizza[name]")%>
  <br><br>
  <%= label_tag("pizza[restaurant]", "Restaurant name:")%>
  <%= select_tag("pizza[restaurant]", options_from_collection_for_select(@restaurants, :id, :name)) %>
  <br><br>
  <%= label_tag("pizza[topping]", "Topping 1:")%>
  <%= text_field_tag ("pizza[topping][]") %> 
  <br><br>
  <%= label_tag("pizza[topping]", "Topping 2:")%>
  <%= text_field_tag ("pizza[topping][]") %> 
  <br><br>
  <%= label_tag("pizza[topping]", "Topping 3:")%>
  <%= text_field_tag ("pizza[topping][]") %> 
  <br><br>
  <%= label_tag("pizza[vegetarian]", "Vegetarian?:")%> 
  <%= select_tag("pizza[vegetarian]", options_for_select([true, false])) %> 
  <br><br>
  <%= submit_tag "Edit my Pizza!" %>
  <%end%>

app/views/pizzas/index.html.erb
<!DOCTYPE html>
<html>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

#myImg {
  border-radius: 5px;
  cursor: pointer;
  transition: 0.3s;
}

#myImg:hover {opacity: 0.7;}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (image) */
.modal-content {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
}

/* Caption of Modal Image */
#caption {
  margin: auto;
  display: block;
  width: 80%;
  max-width: 700px;
  text-align: center;
  color: #ccc;
  padding: 10px 0;
  height: 150px;
}

/* Add Animation */
.modal-content, #caption {  
  -webkit-animation-name: zoom;
  -webkit-animation-duration: 0.6s;
  animation-name: zoom;
  animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
  from {-webkit-transform:scale(0)} 
  to {-webkit-transform:scale(1)}
}

@keyframes zoom {
  from {transform:scale(0)} 
  to {transform:scale(1)}
}

/* The Close Button */
.close {
  position: absolute;
  top: 15px;
  right: 35px;
  color: #f1f1f1;
  font-size: 40px;
  font-weight: bold;
  transition: 0.3s;
}

.close:hover,
.close:focus {
  color: #bbb;
  text-decoration: none;
  cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
  .modal-content {
    width: 100%;
  }
}
</style>
</head>
<body>
<center>
<img id="myImg" src="https://www.crushpixel.com/static16/preview2/pizza-hand-drawn-cartoon-doodles-2371845.jpg" alt="Pizza by Google" style="width:100%;max-width:900px">
</center>

<!-- The Modal -->
<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>

<script>
// Get the modal
var modal = document.getElementById("myModal");

// Get the image and insert it inside the modal - use its "alt" text as a caption
var img = document.getElementById("myImg");
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
  modal.style.display = "block";
  modalImg.src = this.src;
  captionText.innerHTML = this.alt;
}

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
  modal.style.display = "none";
}
</script>

</body>
</html>

<body>
<center>
<p style="font-size:80px ; color:white ; font-family:'Impact'">PIZZA GALORE</p>
</center>
</body>

 <h2> <%= link_to "CREATE NEW PIZA HERE!", new_pizza_path, style: "color:white;" %> </h2>
<ul style="font-size:20px ; color:#AC8070 ; font-family: 'Impact'">

    <% @pizzas.each do |pizza|%>
    
    <li>
    <%= link_to pizza.name, pizza_path(pizza), style: "color: white;" %>
    </li>   
    <%end%>
</ul>

app/views/pizzas/new.html.erb
<center><h1 style="font-size:50px ; color:#A62E02 ; font-family:'Impact'"> MAKE YOUR PIZZA : </h1>

<%= render partial: "pizza_form", locals: {button_text: "Create a Brand New Pizza!", pizza: @pizza} %>

<br><br>
<%= link_to "NAH I CHANGED MY MIND", pizzas_path, style: "font-size:20px ; color:#AC8070;" %> </center>

app/views/pizzas/show.html.erb
<center><h1 style="font-size:55px ; color:#A62E02 ; font-family: 'Impact'"> <%= @pizza.name.upcase %> </h1>
<ul>
<h2 style="font-size:35px ; color:#D4731E ; font-family: 'Impact'"> Restaurant Name: </h2> 
<% if @pizza.restaurant %> 
<h1><%= link_to @pizza.restaurant.name, restaurant_path(@pizza.restaurant), style: "color: white;"%></h1>
<% else %>
<%= "none"%> 
<%end%>

<h2 style="font-size:35px ; color:#D4731E ; font-family: 'Impact'"> Toppings: </h2>
<% @pizza.toppings.each do |topping| %> 

  <li><p style="font-size:20px ; color:white ; font-family:'Impact'">
 <%= topping.name %></p>
  </li>

<%end%>
<h2 style="font-size:35px ; color:#D4731E ; font-family: 'Impact'"> Vegetarian?  </h2> <p style="font-size:20px ; color:white ; font-family:'Impact'"><%= @pizza.display_veg %>
<br><br>
<%= link_to ("Back to Pizzas"), pizzas_path, style: "color: white;" %> 
</ul>
<br><br>
<%= link_to ("Edit this Pizza"), edit_pizza_path, style: "color: white;" %> 
<br><br>
<%= link_to ("Destroy Pizza"), pizza_path(@pizza.id), style:"color:white;", 
method: "delete", 
data: {:confirm => "Are You Sure?"} %>
</center>

app/views/restaurants/index.html.erb
<h1> All Restaurants </h1>

<ul>
    <% @restaurants.each do |restaurant|%>
        <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>   
    <%end%>
</ul>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %></h1>
<ul>
<% @restaurant.pizzas.each do |pizza|%>
  <li><%= link_to pizza.name, pizza_path(pizza) %></li>   
<%end%>
<br><br>
</ul>
<h4><%= link_to ("Go Back To Restaurants"), restaurants_path%></h4>